package entidades;
// Generated 24/02/2017 08:57:36 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Competidor generated by hbm2java
 */
public class Competidor  implements java.io.Serializable {


     private Integer codCompetidor;
     private String nome;
     private String categoria;
     private String telefone;
     private String email;
     private String numberPlay;
     private String idTag;
     private Date horario;
     private Date largada;
     private Date chegada;
     private Date tempoCorrida;

    public Competidor() {
    }

    public Competidor(String nome, String categoria, String telefone, String email, String numberPlay, String idTag, Date horario, Date largada, Date chegada, Date tempoCorrida) {
       this.nome = nome;
       this.categoria = categoria;
       this.telefone = telefone;
       this.email = email;
       this.numberPlay = numberPlay;
       this.idTag = idTag;
       this.horario = horario;
       this.largada = largada;
       this.chegada = chegada;
       this.tempoCorrida = tempoCorrida;
    }
   
    public Integer getCodCompetidor() {
        return this.codCompetidor;
    }
    
    public void setCodCompetidor(Integer codCompetidor) {
        this.codCompetidor = codCompetidor;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getNumberPlay() {
        return this.numberPlay;
    }
    
    public void setNumberPlay(String numberPlay) {
        this.numberPlay = numberPlay;
    }
    public String getIdTag() {
        return this.idTag;
    }
    
    public void setIdTag(String idTag) {
        this.idTag = idTag;
    }
    public Date getHorario() {
        return this.horario;
    }
    
    public void setHorario(Date horario) {
        this.horario = horario;
    }
    public Date getLargada() {
        return this.largada;
    }
    
    public void setLargada(Date largada) {
        this.largada = largada;
    }
    public Date getChegada() {
        return this.chegada;
    }
    
    public void setChegada(Date chegada) {
        this.chegada = chegada;
    }
    public Date getTempoCorrida() {
        return this.tempoCorrida;
    }
    
    public void setTempoCorrida(Date tempoCorrida) {
        this.tempoCorrida = tempoCorrida;
    }

    public String toString(){
        return nome;
    }



}


